version: '3.8'

services:
  app:
    build: ./server  # <-- Вот здесь меняем точку на ./server
    restart: always
    env_file:
      - .env
    expose:
      - "5000"
  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"     # Нужен для HTTP-вызовов Let's Encrypt и редиректов
      - "443:443"   # Основной порт для HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  # Сохраняем сертификаты, чтобы не получать бан от Let's Encrypt при частых деплоях
  caddy_data:
  caddy_config: