name: Continuous Deployment (Callisto VPS)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploying code via SSH to Callisto VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 176.98.177.3          # Прописали IP напрямую
          username: root              # Прописали пользователя напрямую
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Ключ по-прежнему берем из секретов
          port: 22
          script: |
            echo "--- Подключаемся к директории проекта ---"
            cd ~/rso-portal
            
            echo "--- Стягиваем свежий код из Git ---"
            git pull origin main
            
            echo "--- Запускаем пересборку Docker контейнеров в фоне ---"
            docker compose up -d --build
            
            echo "--- Очищаем неиспользуемые старые образы Docker ---"
            docker image prune -f
            
            echo "🚀 Автодеплой успешно завершен! Портал обновлен."